# Generated by Django 3.2 on 2021-04-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerbata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Yerba Mate', max_length=255),
        ),
    ]
