# Generated by Django 3.2 on 2021-04-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yerbata', '0004_auto_20210426_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
