# Generated by Django 3.2 on 2021-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerbata', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read..', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Single Malt', max_length=255),
        ),
    ]
