# Generated by Django 3.2 on 2021-04-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerbata', '0008_auto_20210426_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
