# Generated by Django 3.2 on 2021-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerbata', '0009_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Single Malt', max_length=255),
        ),
    ]
